apiVersion: v1
kind: Pod
metadata:
  name: redis-server
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    readinessProbe:
      exec:
        command: 
          - redis-cli
          - ping
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
    livenessProbe:
      tcpSocket:
        port: 6379
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
    startupProbe:
      tcpSocket:
        port: 6379
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 10
