apiVersion: v1
kind: Pod
metadata:
  name: cpu-mem-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: redis
      image: redis:5.0.3-alpine
      resources:
        limits:
          memory: 600Mi
          cpu: 1
        requests:
          memory: 300Mi
          cpu: 500m

