apiVersion: v1
kind: Pod
metadata:
  name: limitrange-test-nginx
  namespace: limit-range
spec:
  containers:
  - image: nginx
    name: limitrange-test-nginx
    resources:
      requests:
        cpu: 200m
      limits:
        cpu: 200m
