apiVersion: v1
kind: Pod
metadata:
  name: cpu-mem-test
  namespace: cpu-mem-test
spec:
  restartPolicy: Never
  containers:
  - name: cpu-mem-test
    image: najinyang001/stress:latest
    resources:
      requests:
        memory: "100Mi"
        cpu: 1
      limits:
        memory: "500Mi"
        cpu: 2
    command: ["stress"]
    args: ["--vm", "3", "--vm-bytes", "50M", "--vm-hang", "1"]

