apiVersion: v1
kind: ResourceQuota
metadata:
  name: basic-quota
spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
    requests.storage: 10Gi
    persistentvolumeclaims: 10
    services.loadbalancers: 5
    services.nodeports: 10
