apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/kuldeepsingh/Learning/Kubernetes/Local-Setup/kubernetes/Statefulset/data"
