apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-release-matomo-matomo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
