apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
  namespace: default
rules:
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    # we are _not_ including 'create' and 'delete'
    - get
    - list
    - watch
    - update
    - patch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    # so that we can observe our pods getting created
    - get
    - list
    - watch
