apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  selector:
    matchLabels:
      app: blue-deployment
      version: grafana-v1
  replicas: 3
  template:
    metadata:
      labels:
        app: blue-deployment
        version: grafana-v1
    spec:
      containers:
        - name: blue-deployment
          image: grafana/grafana:10.2.8
