apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  selector:
    matchLabels:
      app: green-deployment
      version: grafana-v2
  replicas: 3
  template:
    metadata:
      labels:
        app: green-deployment
        version: grafana-v2
    spec:
      containers:
        - name: green-deployment
          image: grafana/grafana:10.3.7
